// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgGyn9Y3DWtPW7eveQDS-NWgMrAmJmyHE',
    appId: '1:895219304252:web:c89ba2dddf6d9ce797c039',
    messagingSenderId: '895219304252',
    projectId: 'campuspulse-4b82d',
    authDomain: 'campuspulse-4b82d.firebaseapp.com',
    storageBucket: 'campuspulse-4b82d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOx0QaDVZ8y5towdGaAjwkuna-QLD3BDw',
    appId: '1:895219304252:android:44278017af0a4afd97c039',
    messagingSenderId: '895219304252',
    projectId: 'campuspulse-4b82d',
    storageBucket: 'campuspulse-4b82d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI1aJLkWKwgCsllDVdJLipfYqoYSzIyGY',
    appId: '1:895219304252:ios:4e8af2472c38b8ca97c039',
    messagingSenderId: '895219304252',
    projectId: 'campuspulse-4b82d',
    storageBucket: 'campuspulse-4b82d.firebasestorage.app',
    iosBundleId: 'com.example.campusPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI1aJLkWKwgCsllDVdJLipfYqoYSzIyGY',
    appId: '1:895219304252:ios:4e8af2472c38b8ca97c039',
    messagingSenderId: '895219304252',
    projectId: 'campuspulse-4b82d',
    storageBucket: 'campuspulse-4b82d.firebasestorage.app',
    iosBundleId: 'com.example.campusPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgGyn9Y3DWtPW7eveQDS-NWgMrAmJmyHE',
    appId: '1:895219304252:web:5a9fbb5a7964362d97c039',
    messagingSenderId: '895219304252',
    projectId: 'campuspulse-4b82d',
    authDomain: 'campuspulse-4b82d.firebaseapp.com',
    storageBucket: 'campuspulse-4b82d.firebasestorage.app',
  );
}
